---
- name: Run the RHEL 8 STIG
  hosts: all
  roles:
    - name: redhatofficial.rhel8_stig
      sudo_remove_nopasswd: False
      ignore_errors: True

  tasks:
    - name: Update all the packages to the latest
      yum:
        name: "*"
        state: latest
